/**
 * Stable vocabulary for the ApplicationBrief domain contract V1.
 */
class ApplicationBriefConstants {
  static SCHEMA_VERSION = "application-brief-schema-v1";

  static OFFER_REF_KIND = Object.freeze({
    REQUIREMENT: "REQUIREMENT",
    ACTIVITY: "ACTIVITY",
    CONTEXT: "CONTEXT",
    SENIORITY: "SENIORITY",
  });

  static EVIDENCE_KIND = Object.freeze({
    EXPERIENCE: "EXPERIENCE",
    PROJECT: "PROJECT",
    SKILL: "SKILL",
    EDUCATION: "EDUCATION",
    LANGUAGE: "LANGUAGE",
    SOFT_SKILL: "SOFT_SKILL",
  });

  static EVIDENCE_STATE = Object.freeze({
    SUPPORTED: "SUPPORTED",
    PARTIALLY_SUPPORTED: "PARTIALLY_SUPPORTED",
    NOT_EVIDENCED: "NOT_EVIDENCED",
  });

  static PRIORITY = Object.freeze({
    PRIMARY: "PRIMARY",
    SECONDARY: "SECONDARY",
  });

  static CLAIM_TYPE = Object.freeze({
    EXPERIENCE_FACT: "EXPERIENCE_FACT",
    PROJECT_FACT: "PROJECT_FACT",
    SKILL_DECLARATION: "SKILL_DECLARATION",
    EDUCATION_FACT: "EDUCATION_FACT",
    LANGUAGE_DECLARATION: "LANGUAGE_DECLARATION",
    SOFT_SKILL_DECLARATION: "SOFT_SKILL_DECLARATION",
  });

  static CAUTION_KIND = Object.freeze({
    EXPERTISE_LEVEL_UNSUPPORTED: "EXPERTISE_LEVEL_UNSUPPORTED",
    DURATION_UNSUPPORTED: "DURATION_UNSUPPORTED",
    LEADERSHIP_UNSUPPORTED: "LEADERSHIP_UNSUPPORTED",
    LANGUAGE_LEVEL_UNSUPPORTED: "LANGUAGE_LEVEL_UNSUPPORTED",
    SCOPE_GENERALIZATION_UNSUPPORTED: "SCOPE_GENERALIZATION_UNSUPPORTED",
  });
}

export { ApplicationBriefConstants };
